### ISSUE TITLE
sops error

### ISSUE THREAD

**Issue by dkay0670** [erebe/personal-server#15]
Every time I run `sops secrets/.sops.yaml` I get

```
Traceback (most recent call last):
  File "/home/dkay/.local/bin/sops", line 8, in <module>
    sys.exit(main())
  File "/home/dkay/.local/lib/python3.9/site-packages/sops/__init__.py", line 236, in main
    tree, need_key, existing_file = initialize_tree(args.file, itype,
  File "/home/dkay/.local/lib/python3.9/site-packages/sops/__init__.py", line 466, in initialize_tree
    tree, need_key = verify_or_create_sops_branch(tree, kms_arns, pgp_fps,
  File "/home/dkay/.local/lib/python3.9/site-packages/sops/__init__.py", line 604, in verify_or_create_sops_branch
    config = find_config_for_file(path, configloc)
  File "/home/dkay/.local/lib/python3.9/site-packages/sops/__init__.py", line 517, in find_config_for_file
    filename = os.path.basename(filename)
  File "/usr/lib/python3.9/posixpath.py", line 142, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
Do I need to install a python dependency or something?

**Comment by dkay0670** [comment]
Never mind I had the python version installed instead of the go one.

**Comment by dkay0670** [comment]
You might want to add that to the README

**Comment by AvikaTrivedi** [comment]
> Never mind I had the python version installed instead of the go one.

How did you fixed that error ?
